"""added volunteer signup details: full_name, phone, availability, skills, notes

Revision ID: 535a1e08a825
Revises: c0faeae8436d
Create Date: 2026-06-29 11:22:23.085539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '535a1e08a825'
down_revision = 'c0faeae8436d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(), server_default='Not provided', nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=15), server_default='Not provided', nullable=True))
        batch_op.add_column(sa.Column('availability', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('notes')
        batch_op.drop_column('skills')
        batch_op.drop_column('availability')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
