"""Initial Migration

Revision ID: 79adadaaba5f
Revises: 79d512548e52
Create Date: 2026-02-23 22:55:15.987601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79adadaaba5f'
down_revision = '79d512548e52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
