"""ded donation status and checkout_request_id for mpesa confirmation

Revision ID: c0faeae8436d
Revises: c5d66af8eceb
Create Date: 2026-06-27 12:59:11.977977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0faeae8436d'
down_revision = 'c5d66af8eceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=False, server_default='pending'))
        batch_op.add_column(sa.Column('checkout_request_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_donations_checkout_request_id'), ['checkout_request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donations_checkout_request_id'))
        batch_op.drop_column('checkout_request_id')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
